{{- if and .Values.tls.enabled (kindIs "invalid" .Values.tls.clusterIssuer) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.tls.name" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
{{- end }}
